config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers
  resources :schedules
  resources :appointments
  get '/diary', to: "events#diary" 
  root to: 'home#main' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
   validates :user_id, :student_id, :date_time_start, :presence => true
   validate :dates_limit, :dow_accepted_values
   before_create :set_default_time_end, :set_date_zero
   belongs_to :teacher
   belongs_to :student
   has_many :appointments
   scope :range, -> (date_range={}) {
      start_date = date_range[:start_date].nil?  ? "#{DateTime.now.to_date} 00:00:00" : date_range[:start_date] 
      end_date   = date_range[:end_date].nil? ? "#{DateTime.now.to_date} 23:59:59" : date_range[:end_date] 
      wday_nums  = (start_date.to_date .. end_date.to_date).map { |d|
         d.to_date.wday == 0 ? 7 : d.to_date.wday
      }    
      where("date_time_start >= ? AND date_time_end <= ? OR dow_number in (?)", start_date, end_date, wday_nums)
   }
   private
   def set_date_zero
      unless [1..7,nil].include?(self.dow_number)
         self.date_time_start = "0001-01-01 #{date_time_start.strftime("%H:%M:%S")}"
         self.date_time_end = "0001-01-01 #{date_time_end.strftime("%H:%M:%S")}"
      end
   end
   def dates_limit
	  if self.date_time_end != nil && self.date_time_start.to_f > self.date_time_end.to_f
		  errors.add(:date_time_start, 'Date start greater than date end')
	  end
   end
   def set_default_time_end
      if self.date_time_end ==  nil
        self.date_time_end = self.date_time_start + 3600
      end
   end
   def dow_accepted_values
	  unless [1,2,3,4,5,6,7,nil].include?(self.dow_number)
		  errors.add(:dow_number, 'Day of week number out of range (1-7)')
	  end
   end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end
  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:user_id, :student_id, :teacher_id, :date_time_start, :date_time_end, :dow_number)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field form-group">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="field form-group">
    <%= form.label :teacher_id %>
    <%= form.number_field :teacher_id %>
  </div>

  <div class="field form-group">
    <%= form.label :date_time_start %>
    <%= form.datetime_select :date_time_start %>
  </div>

  <div class="field form-group">
    <%= form.label :date_time_end %>
    <%= form.datetime_select :date_time_end %>
  </div>

  <div class="field form-group">
    <%= form.label :dow_number %>
    <%= form.number_field :dow_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Teacher</th>  
      <th>Student</th>
      <th>Date time start</th>
      <th>Date time end</th>
      <th>Dow number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <% teacher = Teacher.find(schedule.teacher_id) %>
        <% student = Student.find(schedule.student_id) %>
        <td><%= schedule.user_id %></td>
        <td> <%= "#{teacher.first_name} #{teacher.last_name}" %> </td>
        <td> <%= "#{student.first_name} #{student.last_name}" %> </td>
        <td><%= schedule.date_time_start %></td>
        <td><%= schedule.date_time_end %></td>
        <td><%= schedule.dow_number %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @schedule.user_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @schedule.student_id %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @schedule.teacher_id %>
</p>

<p>
  <strong>Date time start:</strong>
  <%= @schedule.date_time_start %>
</p>

<p>
  <strong>Date time end:</strong>
  <%= @schedule.date_time_end %>
</p>

<p>
  <strong>Dow number:</strong>
  <%= @schedule.dow_number %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>