config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers
  resources :schedules
  resources :appointments
  get '/diary', to: "events#diary" 
  root to: 'home#main' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <!-- Brand -->
  <a class="navbar-brand" href="#">Logo</a>
  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to 'Registro Diario',  diary_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Agenda</a>
    </li>
    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Registro 
      </a>
      <div class="dropdown-menu">
        <%= link_to 'Alumnos', students_path, class:"dropdown-item" %>
        <%= link_to 'Maestros', teachers_path, class:"dropdown-item" %>
        <a class="dropdown-item" href="#">Usuarios</a>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar'%>
    </br></br></br>
    <div class="wide-container">
      <%= yield %>
    <div>
  </body>
</html>